import Head from "next/head";
import {Footer, Header, HeaderBanners, Loader} from "../../components";
import Image from "next/image";
import Avatar from "../../public/images/avatar.png";
import BgImage from "../../public/images/bg-img.jpg";
import {useAppDispatch, useAppSelector} from "../../core/hooks";
import {Tab, Tabs} from "react-bootstrap";
import {useEffect} from "react";
import {useRouter} from "next/router";
import {useForm} from "react-hook-form";
import {patchUserThunk} from "../../core/store/auth/auth.thunks";
import {IPatchUser} from "../../core/models";
import {toast} from "react-toastify";

const Account = () => {
	// next hooks
	const router = useRouter();

	// redux hooks
	const user = useAppSelector(({auth}) => auth.user);
	const dispatch = useAppDispatch();

	// react hooks
	useEffect(() => {
		const timer = setTimeout(() => {
			if (user) {
				setValue("name", user.name);
				setValue("phone", user.phone);
				setValue("email", user.email);
			} else {
				void router.push({pathname: "/", query: {returnUrl: router.asPath}});
			}
		}, 2000);

		return () => {
			clearTimeout(timer);
		};
	}, [user]);

	// set initial tab
	useEffect(() => {
		if (!router.query.tab) {
			void router.push({query: {tab: "personal"}});
		}
	}, [router.query]);

	// react hook form
	const {register, handleSubmit, setValue} = useForm<
		IPatchUser & {oldPassword: string; newPassword: string; checkNewPassword: string}
	>();

	const onTabSelect = (key: string | null) => router.push({query: {tab: key}}, undefined, {scroll: false});

	const onPersonalDataSubmit = async ({
		newPassword,
		checkNewPassword,
		oldPassword,
		...data
	}: IPatchUser & {oldPassword: string; newPassword: string; checkNewPassword: string}) => {
		if (user) {
			if (newPassword) {
				if (newPassword === checkNewPassword) {
					const action = await dispatch(
						patchUserThunk({
							userId: user.id,
							params: {
								oldPassword: oldPassword,
								password: newPassword,
							},
						}),
					);

					if (action.payload) {
						setValue("oldPassword", newPassword);
						setValue("newPassword", "");
						setValue("checkNewPassword", "");
					}
				} else {
					toast.error("Пароли не совпадают");
				}
			} else {
				dispatch(patchUserThunk({userId: user.id, params: data}));
			}
		}
	};

	return (
		<>
			<Head>
				<title> Профиль | {user?.name}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{user ? (
				<>
					<HeaderBanners />

					<Header />

					<section className="personal-data-section">
						<div className="personal-data-section__container container">
							<div className="personal-data-section__banner">
								<Image className="personal-data-section__banner_img" src={BgImage} alt="" unoptimized />
								<div className="personal-data-section__socials">
									<a href="#">
										<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
											<path
												fillRule="evenodd"
												clipRule="evenodd"
												d="M0 13.927C0 20.8126 5.0009 26.5383 11.5414 27.6994V17.6965H8.07899V13.8497H11.5414V10.7716C11.5414 7.30918 13.7724 5.38638 16.9278 5.38638C17.9273 5.38638 19.0053 5.53988 20.0047 5.69338V9.23314H18.2354C16.5423 9.23314 16.158 10.0791 16.158 11.1571V13.8497H19.8512L19.2361 17.6965H16.158V27.6994C22.6985 26.5383 27.6994 20.8138 27.6994 13.927C27.6994 6.26699 21.467 0 13.8497 0C6.23237 0 0 6.26699 0 13.927Z"
												fill="white"
											/>
										</svg>
									</a>
									<a href="#">
										<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
											<path
												d="M13.6807 9.11557C16.192 9.11557 18.2414 11.165 18.2414 13.6763C18.2414 16.1876 16.192 18.237 13.6807 18.237C11.1694 18.237 9.11998 16.1876 9.11998 13.6763C9.11998 11.165 11.1694 9.11557 13.6807 9.11557ZM0.00200993 13.6763C0.00200993 11.7877 -0.0150978 9.91617 0.0909649 8.03099C0.197028 5.84131 0.696549 3.89797 2.29775 2.29676C3.90238 0.692136 5.8423 0.196036 8.03198 0.0899734C9.92058 -0.0160893 11.7921 0.00101767 13.6773 0.00101767C15.5659 0.00101767 17.4373 -0.0160893 19.3225 0.0899734C21.5122 0.196036 23.4555 0.695557 25.0568 2.29676C26.6614 3.90139 27.1575 5.84131 27.2635 8.03099C27.3696 9.91959 27.3525 11.7911 27.3525 13.6763C27.3525 15.5614 27.3696 17.4364 27.2635 19.3215C27.1575 21.5112 26.658 23.4546 25.0568 25.0558C23.4521 26.6604 21.5122 27.1565 19.3225 27.2625C17.4339 27.3686 15.5624 27.3515 13.6773 27.3515C11.7887 27.3515 9.91716 27.3686 8.03198 27.2625C5.8423 27.1565 3.89896 26.657 2.29775 25.0558C0.693127 23.4511 0.197028 21.5112 0.0909649 19.3215C-0.0185192 17.4364 0.00200993 15.5649 0.00200993 13.6763V13.6763ZM13.6807 20.6935C17.5639 20.6935 20.6979 17.5595 20.6979 13.6763C20.6979 9.793 17.5639 6.65902 13.6807 6.65902C9.79741 6.65902 6.66343 9.793 6.66343 13.6763C6.66343 17.5595 9.79741 20.6935 13.6807 20.6935ZM6.37603 8.01046C7.2827 8.01046 8.01488 7.27829 8.01488 6.37162C8.01488 5.46496 7.2827 4.73278 6.37603 4.73278C5.46937 4.73278 4.73719 5.46496 4.73719 6.37162C4.73692 6.58691 4.77913 6.80014 4.86139 6.9991C4.94366 7.19805 5.06436 7.37882 5.2166 7.53106C5.36883 7.68329 5.5496 7.804 5.74856 7.88626C5.94751 7.96853 6.16074 8.01073 6.37603 8.01046V8.01046Z"
												fill="white"
											/>
										</svg>
									</a>
									<a href="#">
										<svg width="31" height="22" viewBox="0 0 31 22" fill="none" xmlns="http://www.w3.org/2000/svg">
											<path
												d="M30.0157 3.35637C29.8412 2.70644 29.4991 2.11374 29.0235 1.63759C28.548 1.16145 27.9557 0.818548 27.306 0.643219C24.9145 1.30515e-07 15.3278 0 15.3278 0C15.3278 0 5.74107 -1.30515e-07 3.34953 0.639797C2.69954 0.814558 2.10697 1.15727 1.63133 1.6335C1.1557 2.10974 0.813738 2.70274 0.639797 3.35295C-1.30515e-07 5.74791 0 10.7431 0 10.7431C0 10.7431 -1.30515e-07 15.7383 0.639797 18.1299C0.992199 19.4505 2.0323 20.4906 3.34953 20.843C5.74107 21.4862 15.3278 21.4862 15.3278 21.4862C15.3278 21.4862 24.9145 21.4862 27.306 20.843C28.6267 20.4906 29.6633 19.4505 30.0157 18.1299C30.6555 15.7383 30.6555 10.7431 30.6555 10.7431C30.6555 10.7431 30.6555 5.74791 30.0157 3.35637ZM12.2827 15.3278V6.15848L20.2203 10.7089L12.2827 15.3278Z"
												fill="white"
											/>
										</svg>
									</a>
									<a href="#">
										<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
											<path
												fillRule="evenodd"
												clipRule="evenodd"
												d="M27.3445 13.6722C27.3445 21.2227 21.2227 27.3445 13.6722 27.3445C6.12175 27.3445 0 21.2227 0 13.6722C0 6.12175 6.12175 0 13.6722 0C21.2227 0 27.3445 6.12175 27.3445 13.6722ZM14.1622 10.0935C12.8325 10.6461 10.1744 11.7912 6.18897 13.5275C5.54182 13.785 5.20229 14.0368 5.17153 14.2829C5.11911 14.6999 5.64094 14.864 6.34962 15.0862C6.44646 15.1169 6.54672 15.1477 6.64927 15.1819C7.34769 15.4086 8.28652 15.6741 8.77416 15.6843C9.21737 15.6935 9.71185 15.5112 10.2576 15.1374C13.981 12.6229 15.9031 11.3525 16.0239 11.3252C16.1093 11.3058 16.2278 11.2807 16.3076 11.3525C16.3873 11.4232 16.3793 11.5576 16.3714 11.5941C16.319 11.814 14.275 13.7155 13.2154 14.6999C12.8849 15.0064 12.6514 15.224 12.6035 15.2742C12.4964 15.3847 12.387 15.4906 12.2822 15.5921C11.6328 16.2164 11.1474 16.6858 12.3096 17.4515C12.8679 17.8195 13.3145 18.1237 13.76 18.4268C14.2465 18.7583 14.7318 19.0887 15.3608 19.5012C15.5203 19.606 15.6729 19.7142 15.8222 19.8202C16.3885 20.2247 16.8978 20.587 17.5267 20.53C17.8913 20.4958 18.2695 20.1529 18.4609 19.1286C18.9133 16.7063 19.8042 11.4608 20.0105 9.29826C20.023 9.11872 20.0154 8.93833 19.9877 8.76049C19.9711 8.61685 19.9012 8.48469 19.7917 8.3902C19.6288 8.25689 19.3758 8.22841 19.2619 8.23069C18.7481 8.2398 17.9596 8.51439 14.1622 10.0935V10.0935Z"
												fill="white"
											/>
										</svg>
									</a>
								</div>
							</div>
							<div className="personal-data-section__information">
								<div className="personal-data-section__information_content">
									<div className="personal-data-section__information_img">
										<Image src={Avatar} alt="" unoptimized />
									</div>
									<div className="personal-data-section__information_name">
										<h2>{user.name}</h2>
									</div>
								</div>
							</div>
						</div>
					</section>

					<section className="personal-info-section">
						<div className="personal-info-section__container container">
							<Tabs activeKey={(router.query.tab as string) ?? ""} onSelect={onTabSelect}>
								<Tab eventKey="personal" title="Личные данные">
									<div className="personal-info-section__tab-pane">
										<div className="personal-info-section__tab-body">
											<div className="personal-info-section__tab-img">
												<button type="button">
													<Image src={Avatar} alt="" unoptimized />
													<div className="personal-info-section__tab-img-item">
														<span>Сменить аватар</span>
													</div>
												</button>
											</div>
											<div className="personal-info-section__tab-info">
												<div className="personal-info-section__tab-title">
													<h4>Обо мне</h4>
												</div>
												<ul className="personal-info-section__tab-list">
													<li>{user.name}</li>
													<li>{user.email}</li>
													<li>{user.phone}</li>
												</ul>
											</div>
										</div>
										<div className="personal-info-section__title">
											<h2>Данные</h2>
										</div>
										<div className="personal-info-section__forms">
											<form onSubmit={handleSubmit(onPersonalDataSubmit)} className="personal-info-section__form">
												<div className="personal-info-section__input form-floating mb-3">
													<input
														type="text"
														className="form-control"
														id="floatingInput"
														placeholder="name"
														{...register("name", {required: true})}
													/>
													<label htmlFor="floatingInput">Name</label>
												</div>
												<div className="personal-info-section__input form-floating mb-3">
													<input
														type="email"
														className="form-control"
														id="floatingName"
														placeholder="Name"
														{...register("email", {required: true})}
													/>
													<label htmlFor="floatingName">Email address</label>
												</div>
												<div className="personal-info-section__input form-floating mb-3">
													<input
														type="tel"
														className="form-control"
														id="floatingPhone"
														placeholder="Phone"
														{...register("phone", {required: true})}
													/>
													<label htmlFor="floatingPhone">Phone</label>
												</div>

												<button className="personal-info-section__btn">Сменить</button>
											</form>
										</div>
									</div>
								</Tab>
								<Tab eventKey="finance" title="Финансы">
									<div className="personal-info-section__tab-pane ">
										<div className="personal-info-section__tab-balances">
											<div className="personal-info-section__tab-balance">
												<h4>Мой баланс:</h4>
												<span>{user.balance ?? 0} сум</span>
											</div>
											<div className="personal-info-section__tab-buttons">
												<button className="personal-info-section__tab-btn" type="button">
													Пополнить
												</button>
												<a href="#">история финансов</a>
											</div>
										</div>
									</div>
								</Tab>

								<Tab eventKey="security" title="Безопасность">
									<div className="personal-info-section__tab-pane">
										<div className="personal-info-section__tab-safety">
											<form onSubmit={handleSubmit(onPersonalDataSubmit)} className="personal-info-section__form">
												<div className="personal-info-section__input mb-3">
													<label htmlFor="exampleFormControlInput1" className="form-label">
														Старый Пароль
													</label>
													<input
														type="password"
														className="form-control"
														id="exampleFormControlInput1"
														placeholder="password"
														defaultValue=""
														{...register("oldPassword")}
													/>
												</div>
												<div className="personal-info-section__input mb-3">
													<label htmlFor="exampleFormControlInput2" className="form-label">
														Новый Пароль
													</label>
													<input
														type="password"
														className="form-control"
														id="exampleFormControlInput2"
														placeholder="password"
														defaultValue=""
														{...register("newPassword")}
													/>
												</div>
												<div className="personal-info-section__input mb-3">
													<label htmlFor="exampleFormControlInput3" className="form-label">
														Повторите пароль
													</label>
													<input
														type="password"
														className="form-control"
														id="exampleFormControlInput3"
														placeholder="password"
														defaultValue=""
														{...register("checkNewPassword")}
													/>
												</div>
												<button className="personal-info-section__tab-btn mb-3">Ввод</button>
											</form>
										</div>
									</div>
								</Tab>
								<Tab eventKey="buyAd" title="Купить рекламу">
									<div className="personal-info-section__tab-pane">
										<div className="personal-info-section__tab-buy">
											<ul
												className="personal-info-section__tab-buy-list nav nav-pills mb-3"
												id="pills-tab"
												role="tablist"
											>
												<li className="personal-info-section__tab-buy-item nav-item" role="presentation">
													<button
														className="nav-link"
														id="pills-profile-tab"
														data-bs-toggle="pill"
														data-bs-target="#pills-profile"
														type="button"
														role="tab"
														aria-controls="pills-profile"
														aria-selected="false"
													>
														Купить баннер
													</button>
												</li>
												<li className="personal-info-section__tab-buy-item nav-item" role="presentation">
													<button
														className="nav-link"
														id="pills-home-tab"
														data-bs-toggle="pill"
														data-bs-target="#pills-home"
														type="button"
														role="tab"
														aria-controls="pills-home"
														aria-selected="true"
													>
														Купить контекстную рекламу
													</button>
												</li>
												<li className="personal-info-section__tab-buy-item nav-item" role="presentation">
													<button
														className="nav-link"
														id="pills-item-tab"
														data-bs-toggle="pill"
														data-bs-target="#pills-item"
														type="button"
														role="tab"
														aria-controls="pills-item"
														aria-selected="true"
													>
														рекламная цепока
													</button>
												</li>
											</ul>
											<div className="tab-content" id="pills-tabContent">
												<div
													className="tab-pane fade show"
													id="pills-profile"
													role="tabpanel"
													aria-labelledby="pills-profile-tab"
												>
													<a className="personal-info-section__tab-buy-link" href="#">
														Выбор размера баннера
													</a>
												</div>
												<div
													className="tab-pane fade show"
													id="pills-home"
													role="tabpanel"
													aria-labelledby="pills-home-tab"
												>
													<a className="personal-info-section__tab-buy-link" href="#">
														Информация
													</a>
												</div>
												<div
													className="tab-pane fade show"
													id="pills-item"
													role="tabpanel"
													aria-labelledby="pills-item-tab"
												>
													<a className="personal-info-section__tab-buy-link" href="#">
														Информация
													</a>
												</div>
											</div>
										</div>
									</div>
								</Tab>
								<Tab eventKey="myAd" title="Моя реклама">
									<div className="personal-info-section__tab-pane">
										<div className="personal-info-section__tab-my-ad">
											<div className="personal-info-section__tab-balances">
												<div className="personal-info-section__tab-balance">
													<h4>Баннер:</h4>
													<span>15$</span>
												</div>
												<div className="personal-info-section__tab-balance">
													<h4>Цепочка:</h4>
													<span>150x600</span>
												</div>
												<div className="personal-info-section__tab-balance">
													<h4>Контекстная реклама:</h4>
													<span>1</span>
												</div>
											</div>
										</div>
									</div>
								</Tab>
							</Tabs>
							<div className="personal-info-section__tab-content tab-content" id="nav-tabContent"></div>
						</div>
					</section>

					<Footer />
				</>
			) : (
				<Loader />
			)}
		</>
	);
};

export default Account;
