import React from "react";
import Head from "next/head";
import {Footer, Header, HeaderBanners} from "../../components";

const BasicPage = () => {
	return (
		<>
			<Head>
				<title>Bull-metrics</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<HeaderBanners />

			<Header />
			<section className="default-section">
				<div className="default-section__container container">
					<div className="default-section__title mb-3">
						<h4>Заголовок</h4>
					</div>
					<div className="default-section__text mb-3">
						<p>
							Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sapiente tenetur ad aperiam unde consectetur
							corrupti. Quod saepe excepturi pariatur vitae incidunt expedita molestiae dolore nostrum magnam. Iusto,
							autem? Ad, amet?
						</p>
					</div>
					<div className="default-section__title mb-3">
						<h4>Заголовок</h4>
					</div>
					<div className="default-section__text mb-3">
						<p>
							Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sapiente tenetur ad aperiam unde consectetur
							corrupti. Quod saepe excepturi pariatur vitae incidunt expedita molestiae dolore nostrum magnam. Iusto,
							autem? Ad, amet?
						</p>
					</div>
					<div className="default-section__title mb-3">
						<h4>Заголовок</h4>
					</div>
					<div className="default-section__text mb-3">
						<p>
							Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sapiente tenetur ad aperiam unde consectetur
							corrupti. Quod saepe excepturi pariatur vitae incidunt expedita molestiae dolore nostrum magnam. Iusto,
							autem? Ad, amet?
						</p>
					</div>
					<div className="default-section__title mb-3">
						<h4>Заголовок</h4>
					</div>
					<div className="default-section__text mb-3">
						<p>
							Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sapiente tenetur ad aperiam unde consectetur
							corrupti. Quod saepe excepturi pariatur vitae incidunt expedita molestiae dolore nostrum magnam. Iusto,
							autem? Ad, amet?
						</p>
					</div>
				</div>
			</section>
			<Footer />
		</>
	);
};

export default BasicPage;
