import Head from "next/head";
import {
	Banner1200x150,
	Banner150x150,
	Banner160x600,
	Banner728x90,
	Footer,
	Header,
	HeaderBanners,
	HeaderChains,
	MainContexts,
} from "../components";

export default function Home() {
	return (
		<>
			<Head>
				<title>Bull-metrics</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<HeaderBanners />
			<HeaderChains />
			<Header />

			<section className="banner-third">
				<Banner1200x150 />
			</section>

			<section className="banner-fourth">
				<div className="banner-fourth__container container">
					<div className="banner-fourth__row row">
						<div className="banner-fourth__left col">
							<Banner160x600 />
							<Banner150x150 />
						</div>
						<div className=" banner-fourth__center col-xl-6 col-sm-12">
							<Banner728x90 />
							<MainContexts />
						</div>
						<div className=" banner-fourth__right col">
							<Banner160x600 />
							<Banner150x150 />
						</div>
					</div>
				</div>
			</section>

			<Footer />
		</>
	);
}
